### ISSUE TITLE
Intrasite navigation/Section browsing/back buttons

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#104]
![Screen Shot 2020-10-16 at 12 13 34 PM](https://user-images.githubusercontent.com/284315/96288441-0d2ee980-0fa9-11eb-8b15-dd6fc8edd6e6.png)

When you get into a browse sub page it's not that clear where you are or how to get back to the main page

we could add "back to events" to the top at a minimum easy fix, but other ideas: 

- Change subnav up a bit so it's more obvious where you are
- breadcrumbs

**Comment by karindalziel** [comment]
I have hopefully improved the nav/subnav a bit

![Screen Shot 2020-10-16 at 3 28 56 PM](https://user-images.githubusercontent.com/284315/96305943-53de0d00-0fc4-11eb-9a5f-dc32a459169d.png)

I think if we add anything else this round it should just be a simple back link at the top of the page. 

![Screen Shot 2020-10-16 at 3 31 00 PM](https://user-images.githubusercontent.com/284315/96306105-a28ba700-0fc4-11eb-8a0a-74eb63df8aff.png)

**Comment by karindalziel** [comment]
Question for Jess/Greg- would it be somewhat easy to add the "back to main News page" shown above? or is that overwriting a lot of orchid templates?

**Comment by karindalziel** [comment]
Lorna would prefer to have the back button if we can figure it out

**Comment by jduss4** [comment]
I think we can probably add something as part of the navigation section if nothing else, but there might be a breadcrumbs placeholder built into Orchid that we can use, too.  I'll check and if it's not easy, move it out of the 'before launch' category

**Comment by jduss4** [comment]
There is an empty partial for breadcrumbs that we can potentially populate.  I'll think a little about how we can programmatically do it, because in general I think it should be doable since the sections all have the same patterns!

**Comment by jduss4** [comment]
Okay, if I put the code in `_breadcrumbs.html.erb` then it ends up in the nav, basically

![image](https://user-images.githubusercontent.com/2480492/104063572-ff60bd00-51c1-11eb-8caf-f8d9dfba38d8.png)

I wonder if instead, since I'm already overriding the titles for #119 , I could put in a little bit of code directly above the `<h1>` business?
