### ISSUE TITLE
Search Result display

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#107]
Karin needs to talk to lorna about how the search results should display for each section

**Comment by karindalziel** [comment]
For all search results, remove bullet, probably format something like Family Letters

For items with multiple people, etc, design so they look separate. Something like  keywords on this page: http://civilwardc.org/texts/cases/med.d1e17490.html In order to do this put a span around each separate result metadata item so Karin can style. 

* Event Search Results: 
    * Author(s): Author1 Author2
    * Poet(s): Poet1 Poet2
    * Type: Type1 Type2
* Poet Search Results
    * Birth Place: 
    * Birth Date: 
    * Death Date: (if available)
    * Education: Education1 Education2 Education3
    * Number of News items: 5 (ask programmers if this is possible)
* Events Search Results
    * Date: 
    * Type: Type1 Type2
    * Poet(s): Poet1 Poet2
    * Location: 
* Works Search Results
    * Author(s): Author1 Author2
    * Year:
    * Type: Type1 Type2
    * Publisher
    * Location
* Commentaries (we didn't talk about this one)
    * Poet(s): Poet1 Poet2
    * Author(s): Author1 Author2

**Comment by karindalziel** [comment]
todo Karin: get feedback on Commentaries

**Comment by jduss4** [comment]
I'm adding "date" to events because I think that will be beneficial for browsing, but I am happy to yank it

**Comment by jduss4** [comment]
You didn't have any settings for news items so I went with:

Author
Date
Poets
Publisher

Also, I was able to get all the poet ones done, I am just relying on the database for that display rather than the API.
