### ISSUE TITLE
Browse items for left sidebars

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#113]
For all: remove "Browse All"
All except Events, remove "Regions"

## News

- Poets
- Decade
- Location
- Publication
- Tags

## Poets

- Country of Nationality
- Region
- Birth Decade
- First Letter of Last Name
- Education

if possible, we should remove the "First Letter of Last Name" here and just put an alphabet browse  on the right below the region browse. If not possible to remove just add other side. 

## Events

- Type
- Poets
- Decade
- Poets
- Location

Remove region unless we need it to power the region on the right

## Works

- Poet (not on here currently, hopefully we can add)
- Author (should be different from above)
- Decade
- Publisher
- Type

## Commentaries

- Poet
- Author
- News Item
- Event
- Work

**Comment by jduss4** [comment]
I accomplished this by following Lorna's requests in the wireframe documents. Once we remove "browse all" we can probably close this issue.
