### ISSUE TITLE
Change decorative boxes to "buttons" on main "in the news" page

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#120]
https://cdrhdev1.unl.edu/african_poetics/inthenews

**Comment by jduss4** [comment]
Can you explain why you want these to be buttons?  It seems as though links is probably a better idea, since they are linking elsewhere at the moment?

**Comment by karindalziel** [comment]
I don't think they have to be literally buttons, they should be links that look like buttons (class="btn")
