### ISSUE TITLE
Locations coordinates update

### ISSUE THREAD

**Issue by DawesL2** [CDRH/african_poetics#122]
I may need to re run the batch location coordinates before the launch. I have deleted some records and I'm not sure if  the coordinates will now be associated with the correct item ID.  Will this be a problem in the. future?

**Comment by jduss4** [comment]
Hi @DawesL2 that's a good question! When we are moving all our changes from development to production, we will have to look into that, but hopefully we can figure out programmatically if things aren't lining up and check before we add the wrong coordinates to various rows.  Hopefully it won't be a problem in the future if, once we've imported the coordinates, you are adding new coordinates directly to the admin interface when creating a new location.

**Comment by karindalziel** [comment]
Do these need to be repopulated with script

**Comment by DawesL2** [comment]
Yes they do.

**Comment by jduss4** [comment]
Lorna will look into adding these via the admin site, and if there is a need for a bulk entry we can talk about it in more detail then!

**Comment by DawesL2** [comment]
I have added the missing coordinates. Apart from some location duplications. Locations are completed.

**Comment by jduss4** [comment]
Awesome, thanks @DawesL2 !  I will close this issue, since there is another issue open for the duplications.
