### ISSUE TITLE
Location Table- authority control

### ISSUE THREAD

**Issue by DawesL2** [CDRH/african_poetics#123]
When adding new Locations- we need to be able to select the location from a drop down list. For all the fields in the location table. This will prevent us putting in duplicate locations. This should also allow us to  bring in the coordinates from locations that are already in the database.

**Comment by karindalziel** [comment]
We're going to research more into global edits for this

**Comment by DawesL2** [comment]
I noticed that we have some duplicate locations. This happens because there is no authority control on the fields. The only field that has an authority check is the Region, field, so when adding a city and country you cannot check to see if it is already added. This happens when you are adding a location through the location table.  SHould I add this to the milestones for the next project?

**Comment by karindalziel** [comment]
@DawesL2 feel free to go ahead and make an issue - I can go back and assign a milestone. I really need to rethink the milestones anyway so it probably doesn't matter a ton right now
