### ISSUE TITLE
New HTML static page

### ISSUE THREAD

**Issue by DawesL2** [CDRH/african_poetics#126]
I need to add a HTML FAQ page to the News site.  I am currently writing the text for this.

**Comment by karindalziel** [comment]
I think the best thing to do is add the content to this issue as another comment. It produces nice HTML we can pull out and paste in.

**Comment by DawesL2** [comment]
Kwame prefers the About page, so we will not do the FAQ's for now. I have placed the ABout text in the google folder  @ https://docs.google.com/document/d/161q7WdGgIEE6Kxv0swDFHm0AKHIdPD9pCFhkqYX_Nzg/edit?usp=sharing

**Comment by karindalziel** [comment]
Duplicate
