### ISSUE TITLE
backend DB -> frontend DB & ES

### ISSUE THREAD

**Issue by jduss4** [CDRH/african_poetics#127]
Since Lorna & team will continue adding to the backend, we will need to:

1. make a separate DB for the frontend
2. write script / documentation to modify the frontend's DB and populate elasticsearch

Ideally it would be something that a cron job could kick off, but lacking that at least a set of clear instructions is a good starting point

**Comment by karindalziel** [comment]
After we get this set done we'll have to ask lorna how often these should push

**Comment by jduss4** [comment]
Moved to admin UI:  https://github.com/CDRH/african_poetics-in_the_news/pull/47

**Comment by jduss4** [comment]
We can look into a cron job once the PR is in.  We will just have to figure out how to run a rake task (which operates in the bundler and rvm environment) with cron.
