### ISSUE TITLE
Broken links on live site

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#128]
Some of the poet links are broken on the live site. May be a disconnect between index and database, probably we should take care of syncing index and database first, rerun, and then see if this is still an issue. 

Example: Click on Soyinka, Wole from this page: https://cdrhdev1.unl.edu/african_poetics/inthenews/poets/search?f%5B%5D=alternative%7CS

**Comment by jduss4** [comment]
This appears to have been fixed somewhere along the line
