### ISSUE TITLE
Draw up page by page in the news changes for approval

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#130]
These should contain all the issues having to do with each page which are kind of spread all over. 

- Change all layouts to match news #91

### Browse
- #104 

### Search
- #107 

(Lorna please check this issue and make sure the search info is correct)

### News
- #112 
- #113

[Wireframe of News Final Changes](https://docs.google.com/drawings/d/1ep62cQHgW8EdkxnhlRP0rLUd5BD8dSptDvVUETiV8LY/edit)

[Wireframe of news internal page](https://docs.google.com/drawings/d/1L9X52tE_0_MJnvbEchDJz2OSTovy9TUpmnzHBHfDYdk/edit)

#### Main
- #113

[Wireframe of Poet Main Page final changes](https://docs.google.com/drawings/d/1qjIq63Gu-4WnRh_P45dUmHBNX233N66_Hmtn7dR8Hkc/edit)

#### Individual Poet
- #39 
- #88 (possible duplicate)
- #111 
- #117

[Wireframe of poet individual page](https://docs.google.com/drawings/d/1Jq2Il5L_38SDAWIY5PSWrVey_QMdai4iDkGQeCNERBU/edit)

### Events
- #113 

[Wireframe of Events main page final changes](https://docs.google.com/drawings/d/1AC0KkZdmiLGw-DIP6Nk78k2I7uqPqCfVI7XNske0u7E/edit)

[Wireframe of event internal page](https://docs.google.com/drawings/d/1kJXd0Z1pYueRBNl6uVytl5VDhiWaiXukcIcp22Xn9Aw/edit)

### Works
- #113
- #114

[Wireframe of Works main page](https://docs.google.com/drawings/d/1MY3FDV60nrjTAilNHLut9rHSgI4nHjwihVsTc5c-JCk/edit)

[Wireframe of work internal page](https://docs.google.com/drawings/d/18Uahw2KB6XqI4WwlGfvG4M-__zdJgcdcY5iksdJb28w/edit)

### Commentaries
- #35 
- #113
- #116

[Wireframe of Commentaries main page](https://docs.google.com/drawings/d/1AUzfnKn8DV64hcEM7omdwUHVmcjkOObVb0ynY01LL2U/edit)

[Wireframe of commentary internal pages](https://docs.google.com/drawings/d/1-xsaDZ_Gjji7S8PxLG_Ge4zxG0K2gVVIwAK0MRJQvbA/edit)

### About
- #110 

(this will be deleted)

**Comment by jduss4** [comment]
Other than the duplicate author / poet issue, these are done
