### ISSUE TITLE
Find link and fix

### ISSUE THREAD

**Issue by jduss4** [CDRH/african_poetics#137]
http://link.galegroup.com/apps/doc/ CS51007207/GDCS?u=linc74325&sid=GDCS&xid=04a3cf1d

**Comment by jduss4** [comment]
This appears in the article "African Ultra-Royalism"

**Comment by jduss4** [comment]
I cannot edit this entry (https://africanpoetics.unl.edu/admin/news_item/78) until we have content types in the database, which I feel unqualified to take a guess at (https://africanpoetics.unl.edu/admin/news_item_content_type)

**Comment by jduss4** [comment]
Lorna is going to look into this and let me know if content types should be removed or made optional

**Comment by DawesL2** [comment]
Ok so I have solved my 'Content Type' issue. I'm not sure if this can be done now.
 So the 'Content Type'  will contain the information about the type of Content that we are accessing
so the Content Types will be:
Manuscript
Monograph
Newspaper
Periodical/Magazine
Photograph
Video
Audio Recording
Other

Right now all these will be assigned "Newspaper"

**Comment by jduss4** [comment]
@DawesL2 I believe that we could do that now, I can put them into the admin database in the content type table.  Would it be helpful if I were to add content type "Newspaper" to all of the current news items?  Or would that be a bad assumption to make overall?  I can do that if it will make your life easier!

**Comment by DawesL2** [comment]
Thanks. Yes please go ahead and add newspaper to all these entries.

**Comment by jduss4** [comment]
Okay!  I will plan on marking every existing news item in the database as a "Newspaper" and populating the Content Types with the list you put above.  Thanks!

**Comment by DawesL2** [comment]
Can you remind me if we will be able to add 'New Content Types' from the admin side at any time?

**Comment by jduss4** [comment]
It looks like that is disabled right now but we can easily re-enable that.  The same is true of any of the tables, if you want to be able to add new locations, etc, and not just edit the existing ones.

**Comment by DawesL2** [comment]
Yes there is the possibility that News Content formats will need to be added as the research grows. - Tweets, blogs etc.  So this is definitely necessary for the tables. Thanks

**Comment by jduss4** [comment]
I populated the content types with your list above, then set all existing news items to be "newspaper," and then was able to remove the return line from the URL that originally led us down this rabbit hole!  :)
