### ISSUE TITLE
About page changes for main site and sub sites

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#153]
reversing this issue https://github.com/CDRH/african_poetics/issues/110, we will re-add about page once Lorna adds the content below.

**Comment by DawesL2** [comment]
Here is the google doc with the About page information. 



[https://docs.google.com/document/d/161q7WdGgIEE6Kxv0swDFHm0AKHIdPD9pCFhkqYX_Nzg/edit?usp=sharing](url)

[Portal About Page .docx](https://github.com/CDRH/african_poetics/files/5905611/Portal.About.Page.docx)

This is the about page for the Portal Site.

**Comment by karindalziel** [comment]
Karin needs to consult with Lorna about what goes where from this doc. there's some test on existing about pages not listed in this doc and some new text, and I'm not sure which goes in which sections. 

For discussions: There are 3 about pages: 

- Main site About
    - currently has credits 
    - [ ] remove image credit
- CAP about
  - has two pages currently: "about the project" and "consulted sources"
- In the news about

**Comment by karindalziel** [comment]
Look to the linked google doc above for details, the word doc is out of date

**Comment by karindalziel** [comment]
## Main Site about: 
https://africanpoetics.unl.edu/about (currently just has the credits)

Make 3 tabs, 
About the Project (NEW) | leave book fund | Technical Details | Credits

## In the news

add about page

## CAP About: 
https://africanpoetics.unl.edu/contemporarypoets/about 
"About the Project |Selection Criteria |Consulted sources
