### ISSUE TITLE
News item locations

### ISSUE THREAD

**Issue by jduss4** [CDRH/african_poetics#169]
Currently we have "location" as a facet on the news items tab which is supposed to be populated via publication. However, there are currently no locations assigned to any of the publications:

![image](https://user-images.githubusercontent.com/2480492/105405718-14414580-5bf1-11eb-98b0-455a60c6b3aa.png)

This information would presumably not take long to fill in, so we may want to make sure that is done before launch and repopulate the search.

**Comment by DawesL2** [comment]
Thanks. Done.
