### ISSUE TITLE
Questions re: database and generalizing

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#171]
Email from Lorna: 
-------
First I want to say thanks for all the work you have done in developing the database for my ‘In the News” project. It is efficient and exactly what I need to do the analysis and exploration that I want to do in this area.

So,  I'm wondering if you can answer a few questions about the APBF news database.  I know there are many ‘out of the box’ databases that are available, so can you explain how you would describe the uniqueness of the database that you developed for this project, and how this could be used as a prototype for such a database.

Also if you were to continue working on this database, what would that look like, what big and small things need to be done to make it a complete finished product, so others could easily use it for this purpose also. I know the scripts are available in Git Hub, but how does such a database go from this stage to a ‘out of box’ tool? I guess that is my question. What kind of development takes place and what does that job look like?

I know these sound like strange questions, but I can’t think of another way of saying this.  I was wondering if either, or both of you would have any time to talk about this, and give me an ‘Elevator’ pitch on this database and its potential for further development.

Thanks. This is a great tool for what I want to do, and if  there is not a tool that does these things already, It’s clear that we should continue working on this tool.

----

Just so we can refer to the questions below, I am numbering them here:

1: can you explain how you would describe the uniqueness of the database that you developed for this project, and how this could be used as a prototype for such a database
2: if you were to continue working on this database, what would that look like, what big and small things need to be done to make it a complete finished product, so others could easily use it for this purpose also
3: how does such a database go from this stage to a ‘out of box’ tool? What kind of development takes place and what does that job look like?

**Comment by karindalziel** [comment]
Question for @DawesL2 : Could you talk a bit by what you mean by "out of the box" tool?

**Comment by DawesL2** [comment]
Ready made database tools.  Don't focus on that term. What I am asking is why did we decided to program a database and use Rails to do this? Could I have found a  tool that does what I needed to do?  I thought these were just simple answers, sorry. I just assume these were questions that you already had answers to.  No need to spend meetings discussing this at all. I have a few other people I am talking to about database development, they may be able to answer. No Problem.

**Comment by karindalziel** [comment]
@DawesL2 No problem! I have actually been thinking on this quite a bit. I guess when I think of "out f the box" tools I think of things like microsoft access and filemaker pro (and maybe some newcomers like airtable)

But the problem is those wouldn't handle what you want "out of the box." Someone would still have to set up all the tables, links, joins, and queries, as well as any customized forms for data entry. The big difference between those tools and the one we used is that there is a graphical user interface to do much of that, so you wouldn't have to come to us for every change. That said, I suspect there would be some limitations as to how much you could do. And when it came to the front end of the website we'd have to export the data somehow to use so that part of the process would not change. 

I think part of the confusion is that this isn't so much a "tool" we built - we used an existing tool, Rails Admin, to provide a front end for a database. But the uniqueness is in the exact specifications to fit your data, and I'm not sure that's generalizable to other projects. 

We're still happy to have a conversation about this though!

**Comment by DawesL2** [comment]
Thanks, this does answer the question, very clearly. Appreciated.

**Comment by karindalziel** [comment]
Just pasting in a follow up here, in case we need to reference. I think we could do better explaining this throughout the CDRH

-----

From Lorna: I am asking this because you mentioned that the database should be a distinct project from the site, and I wondered why, and wondered why were were not putting the development of this in the grant and a separate tool. So I was looking to see if we had some justification for this. If we developed it out fully, so it could be used by others. Its a very good database and you seem to have done this many times before. I was just thinking about getting support for development.

---------

From Karin: 

The In the news section is based on relational data (a bunch of linked tables)
 
The rest of the site I am guessing will be much like the rest of our projects, where the data is document based. The document based datastore makes sense for things that started as documents: poems, archival letters, pictures, newspapers, etc.
 
When we process the in the news section to display, we essentially put it back into a series of “documents” but for ease of data entry, it’s a bunch of tables.
 
This explainer is a good quick read about the difference between the two: https://medium.com/@brandoncomstock40/document-vs-relational-databases-83e3df5611a7
 
Obviously there’s a lot more that goes into it, but that gets at the crux of the difference.

**Comment by karindalziel** [comment]
Sticking another relational vs document explainer here: will add if I find more later https://medium.com/analytics-vidhya/relational-model-vs-document-model-a71cddd6782d
