### ISSUE TITLE
Tag Cloud design

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#176]
@DawesL2 is this the look you had in mind for a tag cloud?

(I squished things a bit because I thought it looked a little better but I could spread out again)

![Screenshot_2021-02-01 News African Poetry Digital Portal(2)](https://user-images.githubusercontent.com/284315/106539829-58232d00-64c4-11eb-842a-446b8dc03100.png)

**Comment by DawesL2** [comment]
Yes that will work for now. Can lower the frequency so we have a smaller  cloud?  Thanks for doing this.

Lorna
