### ISSUE TITLE
Change path of database publishing script

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#186]
Change the database publishign path, it needs to understand where it lives

**Comment by jduss4** [comment]
Basically the issue is that the dev1 and cors1601 paths are slightly different, but the path in the script is hardcoded.  Instead we ought to use bash to say "start from your current location" and do a relative filepath to get to the config file.

**Comment by DawesL2** [comment]
<img width="1513" alt="Screen Shot 2021-02-05 at 10 42 00 AM" src="https://user-images.githubusercontent.com/52337571/107062871-5a74d800-679f-11eb-8b8c-6f63cfccc4a8.png">
<img width="1226" alt="Screen Shot 2021-02-05 at 10 14 42 AM" src="https://user-images.githubusercontent.com/52337571/107062914-6791c700-679f-11eb-9abf-021c869ece98.png">


The people link is broken

**Comment by jduss4** [comment]
People link has been fixed, the original issue remains

**Comment by karindalziel** [comment]
@DawesL2 see above - if you refresh that broken link should be fixed
