### ISSUE TITLE
Add people to credits 

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#187]
- Claire Jimenez, African Poets and Poetry in the News

under "Research Assistants" 

on https://africanpoetics.unl.edu/about/credits

**Comment by DawesL2** [comment]
On the News About Page please add the following people 

Research Assistants
Susie Rand. University of Nebraska. 
Claire Jimenez University of Nebraska. 


Contributors
Jamaica Baldwin, University of Nebraska. Commentaries. 2020
Saddiq Dzukogi. University of Nebraska. Commentaries. 2020
Olufunke Ogundimu. University of Nebraska. Commentaries. 2020
Jessica Poli.UNL  University of Nebraska. Commentaries. 2020
Zainab Saleh.UNL. University of Nebraska. Commentaries. 2020

**Comment by karindalziel** [comment]
@DawesL2 to be clear: 

You want these people added to the bottom of this page? https://africanpoetics.unl.edu/inthenews/about

and you do NOT want them added to this page? https://africanpoetics.unl.edu/about/credits

it will help in the future if you just paste in the URL to the page yo want things added (if it exists already) so I know for sure. 

thanks!

**Comment by DawesL2** [comment]
Correct.

Leave this page  https://africanpoetics.unl.edu/about/credits <https://africanpoetics.unl.edu/about/credits> as is
