### ISSUE TITLE
Book fund link

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#190]
@DawesL2 I noticed that the link to the african poetry book fund on the home page (https://africanpoetics.unl.edu/) is broken. Would you rather it links to the actual apbf page or the about apbf on the afdp site (https://africanpoetics.unl.edu/about/africanpoetrybookfund)? 

Also would you like me to add a link to the apbf to the apbf about page? (https://africanpoetics.unl.edu/about/africanpoetrybookfund)

If the answer to the above is yes, is this the correct link? https://africanpoetrybf.unl.edu/

**Comment by karindalziel** [comment]
Note: there are other broken links on the main page, Karin will fix these Monday

**Comment by DawesL2** [comment]
Yes Karin, that is the correct link, and yes please add.

thanks
