### ISSUE TITLE
Other Broken Links

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#191]
- viaf link missing http 
    - https://africanpoetics.unl.edu/contemporarypoets/item/ap.per.00127
    - https://africanpoetics.unl.edu/contemporarypoets/item/ap.per.00274
- "Index of Contemporary African Poetry" https://africanpoetics.unl.edu/
- Gale Link
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.161
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.136
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.23
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.95
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.109
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.223
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.276
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.236
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.267
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.213
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.216
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.199
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.221
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.241
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.260
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.238
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.261
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.274
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.227
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.219
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.220
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.183
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.268
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.237
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.258
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.246
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.249
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.263
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.254
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.262
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.251
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.191
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.189
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.184
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.264
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.187
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.266
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.265
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.253
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.259
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.270
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.275
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.190
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.211
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.273
- 2 items with same gale link, both broken
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.244
    - https://africanpoetics.unl.edu/inthenews/news/ap.news.245
- Item links
    - "How is it that things haven't ..." https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=how+is+it+that+things&f%5B%5D=keywords%7Caward
    - "John Littlewood's..." https://africanpoetics.unl.edu/inthenews/news/search?f%5B%5D=keywords%7Cparody
    - "Nigerian Play..." https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=nigerian+play+for+court+theater&f%5B%5D=keywords%7Ccomedy
    - "Progress in Nigeria since civil war" https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=progress+in+nigeria+since+civil+war&f%5B%5D=keywords%7CBiafra
    - "Literature as symptom" first link: https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=+Moore%2C+Gerald+literature+symptom+1963+embarassing
    - https://africanpoetics.unl.edu/inthenews/news/search?f%5B%5D=keywords%7Cdetention
    - https://africanpoetics.unl.edu/inthenews/news/search?f%5B%5D=keywords%7CElizabethan
    - https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=hain&f%5B%5D=keywords%7Cprisoner
    - first link: https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=%27Boycott+threat+to+Games%27%2C+The+Times+%281970%29&f%5B%5D=keywords%7Cdemonstration
    - first link: https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=%27Boycott+threat+to+Games%27%2C+The+Times+%281970%29&f%5B%5D=keywords%7Cdemonstration
    - first link: https://africanpoetics.unl.edu/inthenews/news/search?f%5B%5D=keywords%7Cmodern
    - "new writers emerge" https://africanpoetics.unl.edu/inthenews/news/search?f%5B%5D=keywords%7Cheinemann
    - "african exports" https://africanpoetics.unl.edu/inthenews/news/search?f%5B%5D=keywords%7Cvernacular
    - https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=elysee&f%5B%5D=keywords%7Cexile
    - first link: https://africanpoetics.unl.edu/inthenews/works/search?utf8=%E2%9C%93&q=Christopher+Okigbo%3A+Creative+Rhetoric+%281972%29&f%5B%5D=topics%7C1970
    - under "Mentioned Works (63)" Wole Soyinka: Modern African writers (1978) (Mentioned Poet)  https://africanpoetics.unl.edu/inthenews/poets/ap.person.9
-

**Comment by karindalziel** [comment]
I will leave it at this for now. 

categories: 

1: gale links: maybe we can normalize spaces?
2: viaf: fix in csv and rerun
3: item errors: see: https://africanpoetics.unl.edu/inthenews/news/search?f%5B%5D=keywords%7Cparody 

once we fix the above I'll rerun a link check, it may be these are mostly the same error

**Comment by jduss4** [comment]
VIAF fixed here:  https://github.com/CDRH/data_african_poetics/commit/c86055783a179fec90d9a8c456b763c7c37c6e99

**Comment by jduss4** [comment]
Addressed some of these here:
https://github.com/CDRH/african_poetics/commit/d9f755e66424ebd673481d2eeee889d6649f9dc6
https://github.com/CDRH/african_poetics/commit/165ef0f43f06942da7d3194bb6ec5d934df98cf9
https://github.com/CDRH/african_poetics/commit/96b99159820e1a2b546cc14e85241f1a58efdbb3

**Comment by karindalziel** [comment]
Adding dev links here so I can spot check 

- viaf link missing http 
    - https://cdrhdev1.unl.edu/african_poetics/contemporarypoets/item/ap.per.00127
    - https://cdrhdev1.unl.edu/african_poetics/contemporarypoets/item/ap.per.00274
- "Index of Contemporary African Poetry" https://cdrhdev1.unl.edu/african_poetics/
- Gale Link
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.161
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.136
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.23
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.95
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.109
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.223
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.276
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.236
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.267
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.213
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.216
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.199
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.221
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.241
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.260
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.238
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.261
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.274
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.227
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.219
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.220
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.183
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.268
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.237
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.258
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.246
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.249
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.263
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.254
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.262
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.251
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.191
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.189
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.184
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.264
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.187
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.266
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.265
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.253
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.259
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.270
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.275
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.190
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.211
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.273
- 2 items with same gale link, both broken
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.244
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.245
- Item links
    - "How is it that things haven't ..." https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?utf8=%E2%9C%93&q=how+is+it+that+things&f%5B%5D=keywords%7Caward
    - "John Littlewood's..." https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?f%5B%5D=keywords%7Cparody
    - "Nigerian Play..." https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?utf8=%E2%9C%93&q=nigerian+play+for+court+theater&f%5B%5D=keywords%7Ccomedy
    - "Progress in Nigeria since civil war" https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?utf8=%E2%9C%93&q=progress+in+nigeria+since+civil+war&f%5B%5D=keywords%7CBiafra
    - "Literature as symptom" first link: https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?utf8=%E2%9C%93&q=+Moore%2C+Gerald+literature+symptom+1963+embarassing
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?f%5B%5D=keywords%7Cdetention
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?f%5B%5D=keywords%7CElizabethan
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?utf8=%E2%9C%93&q=hain&f%5B%5D=keywords%7Cprisoner
    - first link: https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?utf8=%E2%9C%93&q=%27Boycott+threat+to+Games%27%2C+The+Times+%281970%29&f%5B%5D=keywords%7Cdemonstration
    - first link: https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?utf8=%E2%9C%93&q=%27Boycott+threat+to+Games%27%2C+The+Times+%281970%29&f%5B%5D=keywords%7Cdemonstration
    - first link: https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?f%5B%5D=keywords%7Cmodern
    - "new writers emerge" https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?f%5B%5D=keywords%7Cheinemann
    - "african exports" https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?f%5B%5D=keywords%7Cvernacular
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/search?utf8=%E2%9C%93&q=elysee&f%5B%5D=keywords%7Cexile
    - first link: https://cdrhdev1.unl.edu/african_poetics/inthenews/works/search?utf8=%E2%9C%93&q=Christopher+Okigbo%3A+Creative+Rhetoric+%281972%29&f%5B%5D=topics%7C1970
    - under "Mentioned Works (63)" Wole Soyinka: Modern African writers (1978) (Mentioned Poet)  https://cdrhdev1.unl.edu/african_poetics/inthenews/poets/ap.person.9
-

**Comment by karindalziel** [comment]
spot check went well, will do link check after pushed to live server again
