### ISSUE TITLE
add gale thumbnails

### ISSUE THREAD

**Issue by sgar7** [CDRH/african_poetics#203]
Gale has given us permission to use whatever size image we want.

Lorna has asked us to add image thumbnails to the item record, and to also embed the link from Gale in the image.

**Comment by sgar7** [comment]
Send Lorna an example of the thumbnail images before we upload en masse.

**Comment by karindalziel** [comment]
1. use data from csv in data_african_poetics/scripts/gale_ingest/output/api_data.csv field image_url
2. write a script that will process images
  1. download the image
  2. determine image type
  3. change image to jpg
  4. resize the image (using a method like "fit") to 120px, probably using the ImageMagick library (or GraphicsMagick)
  5. save the image to a source/images/gale 
3. write a script that will either create a new csv or add to the `source/csv/news items.csv` that list the images
4. Adding the image to the index via the post script
5. display the images on the front end
