### ISSUE TITLE
Airtable to ES Project

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#206]
I believe this will happen in three stages: 

1: Pull data down
2: Ingest data into ElasticSearch
3: Rework rails interface to pull data from API

I imagine you might only be involved in steps 1 and 2

---

LINKS

African Poetry Digital Archive Data Repository:  https://github.com/CDRH/data_african_poetics/

African Poetry Digital Archive Data Rails Repository: https://github.com/CDRH/african_poetics/

- Note, we keep the issues here, and I will be adding this info there
	
Existing Airtable data pull script: https://github.com/CDRH/data_habeascorpus/blob/dev/scripts/python/json_to_csv.py 

- This is what Will Dewey has worked on so far, it pulls down data and creates a CSV to read from
	
Airtable API docs: https://airtable.com/api

Airtable African Poetry Digital Portal Base: https://airtable.com/appbCdwNKqVALtKix

- I don't think you'll be able to see this until I get you access to the Airtable Org we are in with your airtable emails
	
Spreadsheet to track the Airtable column names and match to elasticsearch field names: https://docs.google.com/spreadsheets/d/1e2BOYuW_i8CH07-TZV4FnY01XKELlEDYwdFlRx7QuHQ/edit?usp=sharing

- I have not started filling this out, Sarita and I will start early next week

**Comment by karindalziel** [comment]
I have taken a first stab at adding the info about what Airtable fields will go into which API fields

https://docs.google.com/spreadsheets/d/1e2BOYuW_i8CH07-TZV4FnY01XKELlEDYwdFlRx7QuHQ/edit#gid=0

Anything that is a join field we will need to create a text field that can be parsed into discernible values. Look to Habeas as an example

**Comment by srickel1** [comment]
we have begun pulling the basic fields into csv, and will move on to the joins next.  Can you let us know when/which tables will have the mapping information firmed up?
