### ISSUE TITLE
News items: add data to api from pulled CSVs, following field names on spreadsheet

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#223]
Add pulled down data from #219 to the API - there will probably be questions in this step about how the data will be manipulated

Airtable Column | API field | Interface Term(s) | browse, view | Notes
-- | -- | -- | -- | -- 
contributor.name | contributor.name | browse: African Poet| browse | 
creator.name | creator.name | Author | browse, view | 
topics-decade | topics | Decade | browse | 
publisher | publisher | browse: Publication view: included in "Citation" field | browse, view | changed from "source"
Tags | keywords | Tags | browse, view | 
Document type | type | Browse: News Format View: Type | browse, view | was "format" change to "type"
title | title |  | view | 
unique_id | identifier |  | view | 
Article title | alternative |  | not currently displaying |  
Content type |  |  |  | skip for now, not being used in frontend
Article Date (formatted) | date | Under "Published" and included in "Citation" | view | changed field to pull from so date is formatted correctly no matter how it was entered
Source page no | page_k | in "Citation" | view | 
Source link | rights_uri | in "Citation" | view | 
Gale ID | identifier_original_k |  | | not showing in view currently, included to pull images later
Source access date | date_not_after | in "Citation" | view | 
rights_holder | rights_holder | in "Citation" | view | 
Excerpt | description | Excerpt | view | 
works | works | Works | view | 
subjects | subjects | Events | view | was "topics" but using that for decades
commentaries_relation | relation | Commentaries | view | TODO
Permissions | rights |  | view | ?
person | person.name \| person.role \| person.id | Related People | view |

**Comment by karindalziel** [comment]
Initial notes on processing here - I will list this out by field as I encounter things

### person

pulled from airtable field `person`

I have formatted these entries like this 

`[P'Bitek, Okot](apdp.person.001284)|Poet, [Berry, Neil]()|Critic, [Berry, Neil]()|Author, [Balmires, Harry]()|Editor, [Murry, John Middleton]()|Writer, [Leavis, Frank Raymond 'F. R.']()|Writer, [Montague, Charles Edward 'C. E.']()|Writer, [Wilson, Andrew Norman 'A. N.']()|Writer, [Boyd, William]()|Writer, [Bradbury, Malcolm Stanley]()|Writer, [Lodge, David]()|Writer, [wa Thiong'o, Ngugi 'James']()|Writer, [Lodge, David]()|Writer`

So the rules to process the above should be something like: 

- split on `, ` (note that some names have commas, will need to be careful about splitting outside [] or ()
- check for duplicates - see if there are any strings that match exactly after split
    - in the above made up example, `[Lodge, David]()|Writer` is repeated. I have seen duplicates like this, so I think we'll need a deduplication step
- add to person field
    - part in [] goes in person.name
    - part in () goes in ID (not all items will have an ID)
    - part after | goes in person.role

**Comment by wkdewey** [comment]
What is the TODO for me regarding the date (if there is anything for me to do)?

**Comment by karindalziel** [comment]
@wkdewey I changed the airtable column the date would be pulled from to `Article Date (formatted)` which should cleanup the dates that were entered incorrectly
