### ISSUE TITLE
Events: add data to api from pulled CSVs, following field names on spreadsheet

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#224]
Add pulled down data from #220  to the API - there will probably be questions in this step about how the data will be manipulated 

Airtable Column | API field | Interface Term(s) | browse, view | Notes
-- | -- | -- | -- | -- 
Event type | type | Type | browse | 
person.notpoet | person.name | People | view | no role
person.poet | person.name \| person.id | browse, view | Browse: Poet View: African Poets | manually set role "African Poet"
topics-decade | topics | Decade | browse | 
places | places | Location | browse | 
spatial.region | spatial.region | Region | browse | 
Primary Field | n/a | - | - | 
Name | title | [item title] | view | 
Date not before | date_not_before |  | NONE | we might need to do a range for date not before - date, but current site doesn't have it so hold off
Date | date | Date: | view | 
Summary | description | [callout box] | view | 
spatial.country | spatial.city | Location: | view |
spatial.city | spatial.country | Location: | view | 
Event type | type | Type: | view | 
commentaries_relation | relation | Commentaries | view | 
news_items | medium | News Items | view |

**Comment by wkdewey** [comment]
person.notpoet and person.poet actually have dashes, person-notpoet and person-poet
