### ISSUE TITLE
Works: add data to api from pulled CSVs, following field names on spreadsheet

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#226]
Add pulled down data from #222  to the API - there will probably be questions in this step about how the data will be manipulated 

Airtable Column | API field | Interface Term(s) | browse, view | Notes
-- | -- | -- | -- | -- 
name-major-poet | contributor.name | African Poet | browse | TODO
person-author  | creator.name | Author | browse | TODO
topics-decade | topics | Decade | browse | TODO
Year | date.year | Year | browse | TODO
publisher | publisher | Publisher | browse, view | TODO
Work type | type | Publication Type (browse) Type (view) | browse, view | TODO
Primary Field | title |  | view | 
Title | alternative |  | NONE | This isn't currently used, thought it might be good to have in index just in case
Work type | type | Type | view | 
Year | date_display | Date | view | 
spatial.country | spatial.country | Location | view | 
spatial.region | spatial. region | Location | view | 
Page no | page_k |  | NONE | (SKIP for now, not currently displaying)
Issue | issue_k |  | NONE | (SKIP for now, not currently displaying)
Volume | volume_k |  | NONE | (SKIP for now, not currently displaying)
Source link | rights_uri |  | NONE | not currently used, but is in the airtable, storing in index for now
person | person.name \| person.role \| person.id | Author (role of `Work Author`) People (all other roles) | view | 
news_items | medium | News Items | view | TODO changed from topic, airtable column name stayed the same

person should be pretty straightforward, formatted the same as person in news items (issue #223 )

**Comment by wkdewey** [comment]
Should "type" be split by the "|"?

**Comment by wkdewey** [comment]
It's "spatial.city" not "spatial.region"

**Comment by wkdewey** [comment]
How should news_items/topics be formatted? @karindalziel

**Comment by karindalziel** [comment]
- Should "type" be split by the "|"?
    - yes
- It's "spatial.city" not "spatial.region"
    - yes, thanks for catching. 
- How should news_items/topics be formatted?
    - in general, try to match to current site, it should be similar to how the events are formatted on the news item pages

**Comment by wkdewey** [comment]
Does topics need to be nested? It's not a nested field in the API, I suppose we'll just parse it on the frontend

**Comment by karindalziel** [comment]
@wkdewey yes, I was thinking parse on the front end. Jess thought we had the ability for dynamic multivalued fields, and if so that might be a better solution, but I figured parsing might be an easier solution right now
