### ISSUE TITLE
Airtable cleanup from live site

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#245]
- News - item apdp.news.000785 link is in title field
- News - titles - format them to look like the current site, with just year not full date and with publication name

**Comment by karindalziel** [comment]
The repositories is different, new on left and current production on right

![Screen Shot 2022-07-27 at 9 34 26 AM](https://user-images.githubusercontent.com/284315/181274774-a50c1882-800c-4047-8026-6ba2f3ea6474.png)
t

**Comment by wkdewey** [comment]
I still see some weirdness with the item above: title is showing up as "https://link-gale-com.libproxy.unl.edu/apps/doc/VEZUXX084319804/GDCS?u=linc74325&sid=bookmark-GDCS&xid=496e6ade".
The part about the titles hasn't been implemented yet--I wonder if I need to do something in Datura and/or Rails, in addition to anything that needs to change in Airtable.
