### ISSUE TITLE
Fix low contrast badge count colors

### ISSUE THREAD

**Issue by techgique** [CDRH/african_poetics#256]
Accessibility (a11y) issue (not sure if the label will be created in this repo or not, so including text here)

The badges with item counts on these pages are too low in color contrast:

![image](https://user-images.githubusercontent.com/8347732/194153448-0ab78017-29ae-4808-ae22-9082eb5b8c26.png)

**Comment by karindalziel** [comment]
Done on april_meeting_design branch

![Screen Shot 2023-04-18 at 9 37 46 AM](https://user-images.githubusercontent.com/284315/232811726-9f1d766e-1fd9-4db4-af76-6b43601b570a.png)
