### ISSUE TITLE
create new page

### ISSUE THREAD

**Issue by sgar7** [CDRH/african_poetics#264]
Sarita will create new page for Bibliographies on APDP. They should appear as a button on the home page, titled Digital Bibliographies. This new page should also be part of the main navigation, not the subnavigation. These bibs are currently on Scalar. 

Action items:

- [x] discuss whether to keep on Scalar and link on site or move entirely to APDP
- [x] Discuss with Jason or Greg whether we should move these to CDRH servers
- [x] create page
- [x] add button to home page as pictured below:

![Screen Shot 2022-12-20 at 9 39 31 AM](https://user-images.githubusercontent.com/31414380/208706190-ffdc79aa-1fa9-416d-a2f9-874367419ee5.png)

**Comment by sgar7** [comment]
We will keep Bibs on Scalar.

**Comment by wkdewey** [comment]
What is the current plan for this?
