### ISSUE TITLE
upload 3 more critical commentaries

### ISSUE THREAD

**Issue by sgar7** [CDRH/african_poetics#265]
Funke sent me 8 more critical commentaries that are to be added to this page: https://africanpoetics.unl.edu/inthenews/commentaries/search

Action items:

- [ ] discuss with Karin how to add these (they are in Airtable in HTML)
- [ ] possibility for adding more in the future 
- [ ] discuss text formatting as current commentaries have editing

**Comment by wkdewey** [comment]
These have been uploaded to Airtable and are included in my latest branch. Can I close now? I don't know about the formatting issue though.

**Comment by karindalziel** [comment]
They are in the folder, Karin will add to Airtable and make a new issue about needed metadata
