### ISSUE TITLE
search results showing backend id's

### ISSUE THREAD

**Issue by sgar7** [CDRH/african_poetics#266]
As title suggests, backend IDs are showing up under search results. Links are not getting generated. 
https://africanpoetics.unl.edu/inthenews/poets/search?f%5B%5D=spatial.region%7CSouthern+Africa

**Comment by karindalziel** [comment]
These markdown code needs to be processed and just show the TEXT int he search result, not the ID (don't make it a link)

**Comment by karindalziel** [comment]
@sgar7 what would you think of just showing the number of items - like 

News items: 3

**Comment by karindalziel** [comment]
yes, list NUMBER of news items, but they won't be linked.
