### ISSUE TITLE
Block URL's from showing incorrect ID's

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#268]
https://cdrhdev1.unl.edu/african_poetics/inthenews/poets/item/apdp.work.000001

this has /poets but a /works id, which leads to a broken page 

we should add to the controllers checking `@res` for the ID and sending to 404 if not the correct ID structure

**Comment by wkdewey** [comment]
I fixed the faulty link paths that were causing this problem, but I could also add a check to prevent errors.
