### ISSUE TITLE
Fix site titles

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#27]
I'm leaving the title as "African Poetry Digital Portal" for now, because I couldn't get the titles working before launch. 

Later, re-add this code to layouts/head/_head.html.erb and figure out how to make all titles pull correctly

```html
<title>
    <!-- re-add this --><% if @title.present? %><%= @title %> | <% end %>
    <%= t "general.project_name" %>
  </title>
```

**Comment by karindalziel** [comment]
for clarification, what was happening was on most pages the title was "Title | African Poetry Digital Portal"

**Comment by jduss4** [comment]
Oh.  Okay so this might explain #26
