### ISSUE TITLE
Add commentaries to ES

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#280]
First, research: Are commentaries (https://africanpoetics.unl.edu/inthenews/commentaries) being pulled straight from the ES index? 

If so, we just need to create new entries for the commentaries and add the text as it is currently being added. 

If they are being pulled from an HTML file somewhere (they don't seem to be in /output) then we need to replicate that behavior.

**Comment by wkdewey** [comment]
the commentaries are stored in the html_k field of the API and that is what is displayed in Airtable

**Comment by wkdewey** [comment]
This field (and text) are being populated from the downloaded Airtable data on the Datura side.
