### ISSUE TITLE
Commentaries page, proof of content

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#282]
The commentaries page (https://cdrhdev1.unl.edu/african_poetics/inthenews/commentaries) looks pretty blank. 

A couple of options: 

1. Link to the listing page from the menu instead https://cdrhdev1.unl.edu/african_poetics/inthenews/commentaries/search
2. Add all the listings to the main page below the "search" bar
3. Other?

Gather input from Lorna before making changes

**Comment by elladurham** [comment]
For the April Meeting Milestone, we could hold off on linking to the listing page from the menu and, instead, add this intro text above the “Search Commentaries” search field.  

> Search the collection of critical commentaries and analysis of articles on African poetry published in the London Times, Sunday Times, Financial Times, the Times Literary Supplement 1865–1985. Authored by graduate students from the University of Nebraska-Lincoln.

**Comment by elladurham** [comment]
With PI feedback, let's still add the following intro text between the "Commentaries" heading and the search form. 

> Search the collection of critical commentaries and analysis of articles on African poetry published in the London Times, Sunday Times, Financial Times, the Times Literary Supplement 1865–1985. Authored by graduate students from the University of Nebraska-Lincoln.
