### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#284]
- [x] Visualizations https://cdrhdev1.unl.edu/african_poetics/inthenews/visualizations
- [x] Publisher Join Error
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000499
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000852
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000667
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000619
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000594
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000577
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000580
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000601
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000548
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000783
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000705
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000542
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000729
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000612
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000727
    - https://cdrhdev1.unl.edu/african_poetics/inthenews/news/item/apdp.news.000689

**Comment by wkdewey** [comment]
should close once it is verified these all work on production
