### ISSUE TITLE
Check map on reindex

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#299]
https://africanpoetics.unl.edu/contemporarypoets/browse/keywords

we changed "Middle Africa" to "Central Africa" check to see if map is broken after reingest

**Comment by wkdewey** [comment]
This fixes that region. However, the regions East/Eastern Africa, North/Northern Africa, and West/Western Africa are still broken. (You can click the label on the side, but clicking the map itself brings up 0 hits).

**Comment by elladurham** [comment]
PI input: yes, these can be changed to East, North, West.

**Comment by karindalziel** [comment]
Regions have been renamed in Airtable, repull and ingest

**Comment by wkdewey** [comment]
I see that Southern was changed to South. Don't want to speak for the PI's but I don't think that is correct. "South Africa" usually refers to a country, so the larger region is traditionally "Southern Africa". All the items in In the News and contemporary poets were under "Southern Africa".

**Comment by wkdewey** [comment]
Everything looks good now
