### ISSUE TITLE
Change Browse for CAP

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#300]
- [x]  remove browse as nav
- [x] remove tabs from browse page
- [x] add link to gender browse from main page
- [x] Karin: Style extra browse button

**Comment by wkdewey** [comment]
What does "remove tabs from browse page" mean? I removed the tabs from all the "browse by" pages, though the navbar is still visible here: https://cdrhdev1.unl.edu/african_poetics/contemporarypoets.

**Comment by karindalziel** [comment]
![Screen Shot 2023-04-18 at 11 52 42 AM](https://user-images.githubusercontent.com/284315/232848957-b2a3cce1-a094-4401-98f5-ca72d448ffba.png)
