### ISSUE TITLE
Event facet on In the News Commentaries is blank

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#307]
This has an event

https://cdrhdev1.unl.edu/african_poetics/inthenews/commentaries/item/apdp.commentary.000008

But the facets for event are blank 

https://cdrhdev1.unl.edu/african_poetics/inthenews/commentaries/browse/keywords

**Comment by wkdewey** [comment]
Should be fixed now that I redid the faceting on commentaries
