### ISSUE TITLE
In the News Pages Headings

### ISSUE THREAD

**Issue by elladurham** [CDRH/african_poetics#309]
Edit the headings or add subheadings to the News, Poets, Events, and Works pages for additional context. Provided copy:

> News: News Related to African Poets 
> Poets: Search African Poets 
> Events: Events Related to African Poets
> Works: Works Authored by African Poets

**Comment by karindalziel** [comment]
![Screen Shot 2023-04-18 at 9 52 37 AM](https://user-images.githubusercontent.com/284315/232816263-05e1f15e-1eba-47e1-b705-3a553c55a743.png)

Also see: #305
