### ISSUE TITLE
Thoughts on integrating databases into Orchid

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#31]
We decided for the current known use cases, (mostly african poetics) we can create "documents" from relational CSV's and saved into the data repo. 

For instance, a citation "document" might include the following: (some are fairly standard, some are unique to this project)

Item Title
Source
Source Title
Source Publication Date
Source Page Number
Source Link
Source Access Date
Source Archive
Source Citation

Critic/Reporter
Poet Name (Last, First Middle) [Alternate Name] (poet table) 
Relative | Relationship to Poet (other person)
Mentioned Poets (poet table)
Mentioned, Other | Profession (other person)

Event Title
Event Date
Event Location
Event Type

Coordinates (probably also other place info)

Excerpt
Commentary

Tags

Probably not on event page, but on poet clickthrough:

Poet Publication Details
Poet Pub Type
Mentioned (In) Pub

**Comment by jduss4** [comment]
Decided not to integrate it directly into orchid, but rather into the rails app running on top of orchid for this project
