### ISSUE TITLE
New page: DH Grant

### ISSUE THREAD

**Issue by elladurham** [CDRH/african_poetics#318]
The AP team would like a new page to be created for the dh sub-grants as soon as possible so it can be included in the next call for applicants. They would like the url for the page to be https://africanpoetics.unl.edu/dhgrant and include a project abstract and information about the current grant recipient Dr. Ama Bemma Adwetewa-Badu.

The text is as follows:

>Digital Humanities Grant
Project Abstract
_“Network Poetics: The Big World of African Little Magazines”_ examines African little magazines and turn the names, locations, and works of the poets, artists, and writers into metadata. This metadata will then be visualized through a network model to highlight the expansive nature of African little magazines. By visualizing the data, this project aims to examine how poetry took flight beyond the specificity of regionalism through the vehicle of the little magazine. In so doing, we aim to highlight the ways in which print culture has been a driving force for Black literary practices on the continent and throughout the diaspora. Researchers and users of the network model will be able to manipulate the visuals in order to answer key questions regarding national identity, language, translation, gender, and cultural themes that arise in the study of little magazines.
About Dr. Ama Bemma Adwetewa-Badu
Dr. Ama Bemma Adwetewa-Badu is an Assistant Professor of Black Diasporic Literature and African Literatures in English at Washington University in St. Louis. Her research and teaching focus on topics including contemporary poetry, comparative approaches to Afro-diasporic culture and literature, cultural studies, digital literary cultures, and the digital humanities. 
[Read more about Dr. Adwetewa-Badu](https://artsci.wustl.edu/faculty-staff/ama-bemma-adwetewa-badu)

Mock-up of the new page:

![Screenshot 2023-05-18 at 1 38 41 PM](https://github.com/CDRH/african_poetics/assets/2342978/7f729a4e-29fa-4ed8-97de-45d0c7f42abb)

Photo:

![Adwetewa-Badu](https://github.com/CDRH/african_poetics/assets/2342978/9a371ed7-9eba-41e2-8a64-81603994519f)

**Comment by elladurham** [comment]
@karindalziel made a good point that we may want to consider use the url .edu/dhgrant**s** instead of .edu/dhgrant. Does this need PI input?

**Comment by karindalziel** [comment]
I kinda doubt they would notice if we just use the plural? In the end I don't think it's a huge deal either way, though. 

(since they are putting out a call, I assume information about more grants will be added to this page eventually)
