### ISSUE TITLE
Remove apdp item id from search result text excerpts 

### ISSUE THREAD

**Issue by elladurham** [CDRH/african_poetics#327]
When [searching in the news](https://africanpoetics.unl.edu/inthenews/news/search?utf8=%E2%9C%93&q=ama+ata+aidoo&commit=Search) (Ama Ata Aidoo, for example) apdp item id should not display in the text excerpts / search highlights.

**Comment by erinchambers** [comment]
I believe @wkdewey fixed this, but I will check before closing

**Comment by erinchambers** [comment]
Completed (see dev site)
