### ISSUE TITLE
Broken region map links due to discrepancies in West/ern, North/ern (etc)

### ISSUE THREAD

**Issue by erinchambers** [CDRH/african_poetics#341]
https://africanpoetics.unl.edu/inthenews/poets

Discrepancies in `spatial.region` facet are making the "Search African Poets" regions map point to a faceted search with 0 results, in some cases.
- Map links to "Western Africa" (0 results). "West Africa" has 26 results.
- Map links to "Northern Africa" (0 results).  "North Africa" has 1 result.
- Map links to "Eastern Africa" (0 results). "East Africa" has 10 results.

Not all links are broken.
- "Central Africa" and "Southern Africa" point to the correct faceted search
- The "Regions" list of text links is fine; always takes you to a search page with the correct facet and the same number of items indicated.

**Comment by erinchambers** [comment]
I remember seeing that this had been discussed in the meeting notes somewhere. Was there a decision about "-ern"?

**Comment by wkdewey** [comment]
For now, I am going to change the map so it is consistent with the data

**Comment by wkdewey** [comment]
This is happening on Index of Poets, too
