### ISSUE TITLE
DB: direct relationships of people

### ISSUE THREAD

**Issue by jduss4** [CDRH/african_poetics#36]
Lorna would like to link people directly to people (rather than through works, events, etc) in the cases of things like, spouse, sibling, etc.  Think about how this would look in the database and implement, then add to app's UI.

**Comment by techgique** [comment]
https://github.com/CDRH/african_poetics-in_the_news/commit/6c4e31a0d25117de5bc9958ef768b7ac5f8847b4 and a couple following commits which fixed problems resulting from `object_id` column name conflicting with Ruby core method of the same name
