### ISSUE TITLE
Update Kofi Awoonor Featured Poet ID

### ISSUE THREAD

**Issue by WrenLottmanUNL** [CDRH/african_poetics#377]
After I cleaned up duplicate entries in the Airtable I should have mentioned what the new Kofi ID is. Please change the ID from apdp.person.002188 to apdp.person.001046.

**Comment by wkdewey** [comment]
This should automatically happen after downloading the new Airtable data and re-posting.

**Comment by wkdewey** [comment]
oh, I see this requires a front end change too
