### ISSUE TITLE
October 2024 Rails views sprint

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#388]
We may end up leaving much of this work until December, but it may be worth getting some of it done now. We'll need to alter views to: 

- Update the About pages 
- Copy over any Bibliographies that are done from Omeka S to Rails. We have been using scalar for the Bibliographies, so we'll need to make new views for these. 
- Update the DH grants section of the site

**Comment by erinchambers** [comment]
# About pages
## Updates
- [x] Credits page

## No changes
- Index About
- Index Consulted Sources
- Index Selection Criteria
- News About
- About
- African Poetry Book Fund
- Technical Details

**Comment by erinchambers** [comment]
Done
