### ISSUE TITLE
search view is broken

### ISSUE THREAD

**Issue by wkdewey** [CDRH/african_poetics#391]
It is not linked anywhere but the route still exists. It results in an error on both dev and prod (and my newly upgraded) due to the @section variable not being set. We may just want to exclude it from routes.

**Comment by wkdewey** [comment]
It might be better to exclude the routes but this change does prevent the error when navigating to /search and /browse.

**Comment by erinchambers** [comment]
@wkdewey can we close this issue?

**Comment by karindalziel** [comment]
This appears to be fixed, search is routing back to the home page
