### ISSUE TITLE
Error on Works search page (In the News)

### ISSUE THREAD

**Issue by erinchambers** [CDRH/african_poetics#398]
Search page for Works https://cdrhrailsdev.unl.edu/african-poetics/index-of-poets/search is experiencing an error: `NoMethodError in Items#Index: undefined method '>' for nil:NilClass`

[Items exist](https://cdrhrailsdev.unl.edu/african-poetics/inthenews/works/item/apdp.work.000220) and the Browse pages are all working - it seems to be just the Search pages that are broken.

**Comment by wkdewey** [comment]
It is currently working locally for me. Should test with my changes to the API and the Rails site.

**Comment by wkdewey** [comment]
Unsure of the cause of the error, but this is working now that I've updated the Rails site and the API
