### ISSUE TITLE
Browse by Poet names missing punctuation

### ISSUE THREAD

**Issue by erinchambers** [CDRH/african_poetics#399]
Names on these browse pages are missing the comma between last name and first time (e.g. “Abdullah Fathi” should be “Abdullah, Fathi”), as well as other punctuation (e.g. the apostrophes in ‘Achebe, Chinua ‘Albert Chinualumogu’)

- Index of Poets “Browse by Poet” https://cdrhrailsdev.unl.edu/african-poetics/index-of-poets/browse/title
- In the News “Browse Poets by Name” https://cdrhrailsdev.unl.edu/african-poetics/inthenews/poets/browse/title

Related to #400 

_Note: the names on the Browse News by African Poet have all the correct punctuation https://cdrhrailsdev.unl.edu/african-poetics/inthenews/news/browse/contributor.name_

**Comment by wkdewey** [comment]
I think these are fixed with my recent API changes. It would be necessary to restart the server to see the changes.

**Comment by wkdewey** [comment]
This is now working on the dev server

**Comment by wkdewey** [comment]
I brought cdrhapi.unl.edu/v2 up to date on cors1601 and the issues went away. I will also do the same on cdrhrails.

**Comment by wkdewey** [comment]
looks like cdrhrails api is also up to date (for whatever version we are going to point there)
