### ISSUE TITLE
Browse by Country missing punctuation, sentence case capitalization

### ISSUE THREAD

**Issue by erinchambers** [CDRH/african_poetics#400]
- Punctuation is missing from country names on the Index of Poets “Browse by Country” page (e.g. “Trieste, Kingdom of Italy” or “ São Tomé e Príncipe”)
- Words like ‘of’ and ‘the’ are capitalized in the Browse list, even though they’re lowercase in the data (e.g. “Democratic Republic Of The Congo”)

Related to #399

**Comment by erinchambers** [comment]
@wkdewey this is happening again on the live site: https://africanpoetics.unl.edu/inthenews/poets/browse/spatial.short_name

**Comment by wkdewey** [comment]
Fixed now that I pulled the API on cors1601
