### ISSUE TITLE
In the news - people | Related works not showing up

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#407]
- related works not showing up
	- https://cdrhrailsdev.unl.edu/african-poetics/inthenews/poets/item/apdp.person.000168
	- https://cdrhrailsdev.unl.edu/african-poetics/inthenews/poets/item/apdp.person.000102

**Comment by erinchambers** [comment]
Related works are showing up. New issue: [Stray quotation mark in list of Related Works](https://github.com/CDRH/african_poetics/issues/415)
