### ISSUE TITLE
Index of poets browse

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#411]
Links are broken from the index of poets browse page:

https://cdrhrailsdev.unl.edu/african-poetics/index-of-poets/browse/title

Does not work: 
https://cdrhrailsdev.unl.edu/african-poetics/index-of-poets/search?f[]=title|Pringle+Thomas

Works (this is just from the regular search):
https://cdrhrailsdev.unl.edu/african-poetics/index-of-poets/search?q=title|Thomas+Pringle

**Comment by wkdewey** [comment]
it works for me locally. Probably just need to get Orchid up to date.

**Comment by wkdewey** [comment]
or else the API

**Comment by wkdewey** [comment]
Partially fixed--depends how much you care about the comma in the summary box

**Comment by wkdewey** [comment]
Links are no longer broken. There is still a slight normalization issue ("Pringle Thomas" vs. "Pringle, Thomas") and those tend to be quite time consuming to fix. But it is not broken, so I am going to recommend closing.
