### ISSUE TITLE
Gender field now has 4 values: Male, Female, Man, Woman

### ISSUE THREAD

**Issue by erinchambers** [CDRH/african_poetics#412]
Was this a goof on our end, or on theirs?

Index of Poets has 14 items with gender "Man," and 2 items with gender "Woman"—these are new; all other items have the gender values that existed before, Male and Female

https://cdrhrailsdev.unl.edu/african-poetics/index-of-poets/browse/person_gender_k

**Comment by wkdewey** [comment]
I think I did this

**Comment by wkdewey** [comment]
The code said "if gender equals "M" then return "Male", if gender equals "F" then return "Female"
Well, it no longer said M and F in the spreadsheet, so it was all coming up blank. And it seemed redundant to do "if gender equals 'Male' return 'Male'". So I just ingested the field directly.

**Comment by wkdewey** [comment]
Here is where I made the change: https://github.com/CDRH/data_african_poetics/commit/a6ec80a407354458a7760b29f41b0ea7dd7dd737

**Comment by karindalziel** [comment]
This isn't Will's fault -  we changed how the data is entered to a plain text field. I am going to change all to man and woman for this ingest but make a note for brown that this needs some more consideration. This will mean we need a new pull.
