### ISSUE TITLE
Person not found

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#417]
From the Index of Poets, some are not found when clicked 

- https://africanpoetics.unl.edu/index-of-poets/search?page=1&section=index_of_poets see "Dib, Mohammed " link
- https://africanpoetics.unl.edu/inthenews/poets/search?f%5B%5D=alternative%7CD Davis, Philip Rufus

**Comment by wkdewey** [comment]
IN the first case, this is an error within the page rather than not found.

**Comment by karindalziel** [comment]
It hink that's likely the case for all of them
