### ISSUE TITLE
Markdown parsing error on a work

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#419]
on this work, there is some kind of markdown parsing error

https://africanpoetics.unl.edu/inthenews/works/item/apdp.work.000351

If you click the author or related person, you get a link to 

https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000528)%5BSoyinka%20,%20Wole%20'Akinwande%20Oluwole%20Babatunde'%5D(apdp.person.000930

"No item with identifier apdp.person.000528)[Soyinka , Wole 'Akinwande Oluwole Babatunde'](apdp.person.000930 found! "

### person
`[Rousseau, Ina](apdp.person.itn.000528)[Soyinka , Wole 'Akinwande Oluwole Babatunde'](apdp.person.itn.000930)|Poet;;;[Rousseau, Ina](apdp.person.itn.000528)[Soyinka , Wole 'Akinwande Oluwole Babatunde'](apdp.person.itn.000930)|Work Author`

### [person] (from [work roles])
`[Rousseau, Ina](apdp.person.itn.000528);;;[Soyinka , Wole 'Akinwande Oluwole Babatunde'](apdp.person.itn.000930)`

**Comment by wkdewey** [comment]
I think this is an Airtable issue. Most entries only have a single markdown value associated with a role. My assuption in the code is [Poet name](Poet id)|role, separated by semicolons.
