### ISSUE TITLE
create documentation for using admin site

### ISSUE THREAD

**Issue by jduss4** [CDRH/african_poetics#42]
This is going to be a combination of adding a few lines in the admin site itself (see news_item_roles) and a quick guide in google drive or wherever they prefer.

**Comment by jduss4** [comment]
on it

**Comment by techgique** [comment]
Revised / finalized: https://docs.google.com/presentation/d/1LD6VqP3gQODxG8rX_TDmHXcxsk7yDRhRKBF6UCskDO4/edit#slide=id.g7285512230_0_131
