### ISSUE TITLE
There are a few more errors on poet pages, causing a 404

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#421]
I believe this is a complete list

- [apdp.person.000213](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000213) **El Hadj Belarbi, Sheik Benguedda**
- [apdp.person.000698](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000698) **Adali-Mortty, Geormbeeyi**
- [apdp.person.000744 ](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000744) Coetzee, John Maxwell ' -J. M. '
- [apdp.person.000980](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000980) Krog, Antjie
- [apdp.person.001596](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.001596) **Kuzwayo, Ellen**

This one is an airtable error and shouldn't be linked, so no need to fix
- https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000514

The first step is to look at these entries and see if there is something wrong in airtable causing them, but it would be nice to have a check in place so whatever it is doesn't break the site. That said, this is probably the last push, so if we can fix in airtable it's probably fine.

**Comment by wkdewey** [comment]
all fixed now
