### ISSUE TITLE
Two people still have broken rails views

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#422]
The following people still have unexplained broken rails views

- [apdp.person.000744](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000744) Coetzee, John Maxwell ' -J. M. '
  - linked from (example) https://africanpoetics.unl.edu/inthenews/poets/search?f%5B%5D=alternative%7CC 
  - error in dev https://cdrhrailsdev.unl.edu/african-poetics/inthenews/poets/item/apdp.person.000744
- [apdp.person.000980](https://africanpoetics.unl.edu/inthenews/poets/item/apdp.person.000980) Krog, Antjie
  - linked from (example) https://africanpoetics.unl.edu/inthenews/poets/search?f%5B%5D=alternative%7CK
  - Error in dev https://cdrhrailsdev.unl.edu/african-poetics/inthenews/poets/item/apdp.person.000980

**Comment by wkdewey** [comment]
these are fixed on dev. I haven't put it on production at this point

**Comment by wkdewey** [comment]
working on production too now
