### ISSUE TITLE
differentiate types of pages (works, poets, events, etc)

### ISSUE THREAD

**Issue by jduss4** [CDRH/african_poetics#48]
Right now there's no navbar clues (#45 ) and there also aren't any text indications to tell you what kind of an object you are looking at, so it's a bit confusing.  Is this a work or a news item, for example?  I think we should make that clear somehow to the user.

**Comment by techgique** [comment]
Jess, I think you handled this with the nav indications, yes?

**Comment by jduss4** [comment]
yes sir!
