### ISSUE TITLE
Remove "Source" 

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#7]
this field doesn't mean anything as currently used. Go ahead and take out of API completely.

**Comment by jduss4** [comment]
Out of the entire API?!  I think I do use it for some projects, though!  Just as a glance via cdrhdev's api, it looks like we're using it for Whitman to keep track of things like "Horace Traubel Writes About Whitman Volume 2" and such.

**Comment by karindalziel** [comment]
no no, just this project
