### ISSUE TITLE
add validation for date fields which are not actually datetime

### ISSUE THREAD

**Issue by jduss4** [CDRH/african_poetics#73]
examples include events (integer) and person date_birth and date_death fields (string).

Presumably we want to catch this before a record saves and alert the user that their input was incorrect.  It may not be possible before launch.  Help text added in #57

**Comment by techgique** [comment]
Seeded data for production, then enabled date validations for Person and Event models: https://github.com/CDRH/african_poetics-in_the_news/commit/300bac338fd23849f7b8cd5b3c246a2bc2986f78
