### ISSUE TITLE
Poets Page

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#77]
## Map

Map will change to a region map like we have on this page: https://africanpoetics.unl.edu/contemporarypoets/browse/keywords

The region will be the region for the author's birthplace

Right now there are some extra regions (United Kingdom (5)) but these will be cleaned up before launch and the only regions left will be the 5 african regions. IF NOT, I think as long as the map highlights when an african region is moused over, that's fine. 

## Search 

to do, standard full text search

**Comment by jduss4** [comment]
Text search currently:

name_last
name_given
name_alt
bibliography
short_biography

**Comment by jduss4** [comment]
I believe this work is now completed on branch `apn`.  Note that in order to get the map working, I needed to change the data repo, which now also has an `apn` branch.  You need to populate the index using that branch in order to see the map changes.
