### ISSUE TITLE
Poets Browse Page 

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#78]
https://africanpoetics.unl.edu/inthenews/poets/search

## Facets

This page should have faceting, along the lines of orchid or the cather readings bibliography (https://cather.unl.edu/scholarship/reading_bibliography)

The facets should be:

* country (birth)
* university
* year
* first letter of last name
* region

## Listing

Karin will do some cleanup on this later, but should be something like this

Poet Name
* Birthplace: county, city (region)
* Birth Date: YYYY
* University: University name (YYYY)
* University: University name (YYYY)

**Comment by jduss4** [comment]
Can you clarify what the "year" filter should be?  Year of birth?

**Comment by karindalziel** [comment]
@jduss4 yes, year of birth
