### ISSUE TITLE
Discuss: how to avoid duplicate entries/links that go to the same page

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#88]
![Screen Shot 2020-10-12 at 4 23 10 PM](https://user-images.githubusercontent.com/284315/95791628-6516d900-0ca7-11eb-92ae-c690c85c8713.png)

As an example, from this page: https://cdrhdev1.unl.edu/african_poetics/inthenews/poets/ap.person.2540

Ideally, it would probably look like this: 

- From Mimosa Land (1910) (Poet/Author)

**Comment by karindalziel** [comment]
discuss with lorna

**Comment by jduss4** [comment]
#142 I think some of the solutions here would take care of this

**Comment by jduss4** [comment]
Closing this in favor of the other
