### ISSUE TITLE
Change map to decorative on news page

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#97]
this map does not actually connect to regions, so should be more decorative and not change on hover

**Comment by karindalziel** [comment]
I changed the id around the map to "regions_map_decorative" and that switched it back to color by country. 

Ask @jduss4 about the best way to disable hover colors on just that page.

**Comment by jduss4** [comment]
I think that I got this figured out!  https://github.com/CDRH/african_poetics/pull/100

**Comment by karindalziel** [comment]
Closing since I got rid of the map, sigh
